[gcp_service_account]
type = "service_account"
project_id = "suivi-pepiniere"
private_key_id = "4dc14a951c8b2954fcd160670493a0a2b63f6e81"
private_key = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDORv1Q9QHPZd5K
Y15rJ7N64v/yv5F72KZ8wvVgML+yNXCjYyCWesDsdpZmbuSraWDM52JkMGAsNFQc
veEPf3HlpNmqZuhwBB7xhlBKNnHbswCuB41o1GF9p4X9QhgUksDvNrsKost14cne
y+WzmpGKBdh5gAgYh3s9jm6omAWZYrZHsCV9o0Oxb3XUEBaGVvn9jAt9jOY3zo0F
8ZesBoamMLuBv5/WiYJjZ+ldahk0OfES+bDCssbT1YAPN0kEhlestLYsCssZUrLZ
JMgIMDX/6Sh3yshKd7CZvCF4X8eKjm0sKVlt1w0cQfIywO60bqew/twPK4rFjeIm
YKmG6ottAgMBAAECggEAE3g4Wy6Q8ewtx8wqwobwBhqMaXNi7jNT/YUiR2a6hT3N
iKJn1kQ2VutXhUoUu8gZuqVhUE8PmMSEpuTWLBINpE0DvXVynXYKHKZeiC6s3v19
hC+SzZD0Nbm86BtXrgNvAfUiwN1+Qj1iQizxHJtrfsFP/iHTQctx2qzJrZCRwLkY
v0tu1zKe7k/+4vqtm64xDi7KGewqMqf4TcvQeaIkHTugfju+dr8XQftaCqBWrtHW
r69zBkr7niW6obFLLaoqytfs1KMKqbQ12mftJoNt/HHPCmEG0ev6It+o53CNeyJw
f/GzqSm2JzylgP9jVSQv1B81HYyqx9VkxCV9eySVCQKBgQD01Xozte057DFc0fH+
zcE9nUds2/iIl5AjDl5+WKnPazTxU2GNHgFNqMeFjWImVz6oqscdLmhQKhBghJCp
qRaMRkF4X6rf6fM6aTrvTEcW+bg0ImX+xRMFcr3CoM2LA8yPkGfkzQLkEwn28X2Z
2sjUWka5/pxZ0XslyeAvj20ldQKBgQDXr1mqMtbCJTfsStblTx9VKnvWNqDpL2D2
S0revyf1slRF2LsupWOXDCa8hfIa5aajlqhPM1MQpytIL3NnKvXFdgCI0TYzOhjV
X6sf6Lzz3UelBVygQwzoiHmiyFKO0EglQF5IB9pNpMDiiBFQVoRlz0tUzY4SDH5l
WMbjc+b3GQKBgA3FK/hYlR0a4bPcwwWXwPScMfY3cQUNsTeniT0F85cM6o9gJy5u
r5gUlBQ43XpWkdmesVA82fUYSI+FJTXFotUE5o3Eo7GwUNPKM1xeJ+ls5iVYgfAQ
WX+G8pFNxgG5lvnEH3PI7A6z222eK3hJy93VrgCsB1Mt6wU3E3rZUEQ5AoGBAM8f
JfUKoy+HfD+e0uUcaVNo28knZrjnda6vOTPUz/PjD4iPi5lM2+lWkvBhlNB9jtvz
tqdv+ym3zxmf76u4FpJMMlEwz2K8PNLS70tSPfnVmpJ/JqcEHKZFQMGwq49XtqCH
QsLbP6lmOJCR6EaE/tmiCo5iYzcz5kE+0qfkSn0pAoGBALzI4uSgmmv3Fl3SecU6
mdQ7JFXYrY/JWT+wVts5FG5nvshFtZtGKmBmupLHbM0nJS+LJ0UYJyyvJ06MM0B4
XcCN0CgwgaIOipq+s4XHGKBzvjWYpXfqFGSctT4EibJu/ohfDMvv0uUoX80r9pOp
/6Z+8jZXFz9wg1Nh28M/rOUS
-----END PRIVATE KEY-----"""
client_email = "suivi-pepiniere@suivi-pepiniere.iam.gserviceaccount.com"
client_id = "102902643357221903371"
auth_uri = "https://accounts.google.com/o/oauth2/auth"
token_uri = "https://oauth2.googleapis.com/token"
auth_provider_x509_cert_url = "https://www.googleapis.com/oauth2/v1/certs"
client_x509_cert_url = "https://www.googleapis.com/robot/v1/metadata/x509/suivi-pepiniere%40suivi-pepiniere.iam.gserviceaccount.com"
universe_domain = "googleapis.com"
